import { StyleSheet } from 'react-native';

import { colors } from '@/constants/colors';
import { spacing } from '@/constants/spacing';
import { fontFamily } from '@/constants/typography';

export const reviewStyles = StyleSheet.create({
  screen: {
    flex: 1,
    paddingHorizontal: spacing.lg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  headerSide: {
    width: 72,
    alignItems: 'flex-start',
  },
  headerSideRight: {
    alignItems: 'flex-end',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rim,
    backgroundColor: colors.glass.frostFill,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 10px 26px rgba(0, 0, 0, 0.36)',
  },
  headerSpacer: {
    width: 64,
    height: 34,
  },
  headerCancelButton: {
    minWidth: 64,
    height: 34,
    paddingHorizontal: spacing.sm,
    borderRadius: 17,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.semantic.error,
    backgroundColor: colors.notificationIcon.errorFill,
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.28)',
  },
  headerCancelText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.semantic.error,
  },
  totalsBar: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    borderRadius: spacing.lg,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.strongFill,
    marginBottom: spacing.md,
    gap: 2,
    boxShadow: '0 16px 34px rgba(0, 0, 0, 0.28)',
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.xl,
  },
  rowSkipped: {
    opacity: 0.5,
  },
  tokenPanel: {
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    marginBottom: spacing.xs,
  },
  reviewActionsRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing.sm,
  },
  tokenSelectorBlock: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  addRowButton: {
    height: 56,
    paddingHorizontal: spacing.md,
    borderRadius: 28,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rim,
    backgroundColor: colors.glass.frostFill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    boxShadow: '0 10px 24px rgba(0, 0, 0, 0.26)',
  },
  addRowButtonText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.text.primary,
  },
  tokenSelectButton: {
    height: 56,
    borderRadius: spacing.md,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.clearFill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    boxShadow: '0 12px 28px rgba(0, 0, 0, 0.24)',
  },
  tokenSelectButtonCompact: {
    alignSelf: 'flex-start',
    height: 38,
    minWidth: 124,
    maxWidth: 164,
    borderRadius: 19,
    paddingHorizontal: spacing.sm,
    paddingVertical: 0,
    boxShadow: 'none',
  },
  tokenSelectButtonDisabled: {
    opacity: 0.56,
  },
  tokenSelectTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  tokenSelectText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 13,
    color: colors.text.primary,
  },
  tokenSelectDetail: {
    fontFamily: fontFamily.ui,
    fontSize: 10,
    color: colors.text.tertiary,
  },
  editableRowItem: {
    alignItems: 'flex-start',
    position: 'relative',
    borderBottomWidth: 0,
    borderRadius: spacing.lg,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.clearFill,
    paddingBottom: 64,
    marginBottom: spacing.sm,
    boxShadow: '0 16px 34px rgba(0, 0, 0, 0.2)',
  },
  rowTitleLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  rowNumberBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.frostFill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowNumberText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 11,
    color: colors.text.secondary,
  },
  rowMain: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  rowInput: {
    minHeight: 36,
    borderRadius: spacing.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.smokeWash,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    fontFamily: fontFamily.mono,
    fontSize: 12,
    color: colors.text.primary,
  },
  rowRight: {
    alignItems: 'flex-end',
    gap: 4,
  },
  amountInputWrap: {
    minWidth: 104,
    borderRadius: spacing.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.smokeWash,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    alignItems: 'flex-end',
    boxShadow: '0 10px 22px rgba(0, 0, 0, 0.18)',
  },
  amountInput: {
    minWidth: 64,
    padding: 0,
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
    textAlign: 'right',
  },
  amountSymbol: {
    fontFamily: fontFamily.ui,
    fontSize: 10,
    color: colors.text.secondary,
  },
  skipButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.glass.frostFill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
  },
  skipButtonText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.text.primary,
  },
  rowActionStack: {
    alignItems: 'flex-end',
    gap: 6,
  },
  rowBottomActions: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    bottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  deleteRowButton: {
    minHeight: 30,
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.semantic.error,
    backgroundColor: colors.notificationIcon.errorFill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  deleteRowButtonText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 11,
    color: colors.semantic.error,
  },
  tokenPickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
  },
  tokenPickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glass.depthShadow,
  },
  tokenPickerSheet: {
    maxHeight: '72%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rim,
    backgroundColor: colors.glass.strongFill,
    paddingTop: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
    boxShadow: '0 -18px 40px rgba(0, 0, 0, 0.38)',
  },
  tokenPickerHeader: {
    minHeight: 40,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  tokenPickerCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.frostFill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tokenPickerList: {
    paddingBottom: spacing.sm,
  },
  tokenPickerRow: {
    minHeight: 58,
    borderRadius: spacing.md,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.clearFill,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  tokenPickerRowSelected: {
    borderColor: colors.glass.rim,
    backgroundColor: colors.glass.accentVeil,
  },
  tokenPickerRowPressed: {
    backgroundColor: colors.surface.pressed,
  },
  tokenPickerRowText: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  tokenPickerSymbolRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  tokenPickerSymbol: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
  },
  tokenPickerName: {
    fontFamily: fontFamily.ui,
    fontSize: 12,
    color: colors.text.secondary,
  },
  tokenPickerRowRight: {
    minWidth: 72,
    alignItems: 'flex-end',
    gap: 3,
  },
  tokenPickerBalance: {
    fontFamily: fontFamily.ui,
    fontSize: 12,
    color: colors.text.primary,
  },
  tokenPickerEmpty: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
