import { StyleSheet } from 'react-native';

import { colors } from '@/constants/colors';
import { spacing } from '@/constants/spacing';
import { fontFamily } from '@/constants/typography';

export const payrollStyles = StyleSheet.create({
  card: {
    borderRadius: spacing.lg,
    borderCurve: 'continuous',
    backgroundColor: colors.surface.cardElevated,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rim,
    padding: spacing.lg,
    gap: spacing.md,
    boxShadow: '0 16px 34px rgba(0, 0, 0, 0.28)',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  title: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 16,
    color: colors.text.primary,
    flexShrink: 1,
  },
  sourceName: {
    fontFamily: fontFamily.ui,
    fontSize: 13,
    color: colors.text.secondary,
    flexShrink: 1,
  },
  runStatusHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  runStatusTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  runStatusEyebrow: {
    fontFamily: fontFamily.ui,
    fontSize: 10,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.24,
  },
  runStatusTitle: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 18,
    color: colors.text.primary,
  },
  runStatusPill: {
    minHeight: 30,
    borderRadius: 15,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.clearFill,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  runStatusPillMuted: {
    backgroundColor: colors.surface.backgroundTint,
  },
  runStatusPillText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.text.secondary,
    textTransform: 'capitalize',
  },
  runMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  runMetricPill: {
    minHeight: 34,
    borderRadius: 17,
    borderCurve: 'continuous',
    backgroundColor: colors.surface.backgroundTint,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  runMetricValue: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 13,
    color: colors.text.primary,
    fontVariant: ['tabular-nums'],
  },
  runMetricLabel: {
    fontFamily: fontFamily.ui,
    fontSize: 12,
    color: colors.text.secondary,
  },
  routeSummaryPill: {
    maxWidth: '42%',
    minHeight: 30,
    borderRadius: 15,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    backgroundColor: colors.glass.clearFill,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  routeSummaryText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.text.secondary,
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  statGrid: {
    minHeight: 76,
    borderRadius: spacing.md,
    borderCurve: 'continuous',
    backgroundColor: colors.glass.clearFill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  stat: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xs,
  },
  statCenter: {
    alignItems: 'center',
  },
  statRight: {
    alignItems: 'flex-end',
  },
  statDivider: {
    width: StyleSheet.hairlineWidth,
    alignSelf: 'stretch',
    backgroundColor: colors.glass.rimSubtle,
  },
  walletStrip: {
    minHeight: 36,
    borderRadius: spacing.sm,
    borderCurve: 'continuous',
    backgroundColor: colors.surface.backgroundTint,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  walletValue: {
    flexShrink: 1,
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
  },
  statLabel: {
    fontFamily: fontFamily.ui,
    fontSize: 10,
    color: colors.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 0.18,
  },
  statValue: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
    fontVariant: ['tabular-nums'],
  },
  textCenter: {
    textAlign: 'center',
  },
  textRight: {
    textAlign: 'right',
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.glass.frostFill,
  },
  badgeText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.text.primary,
  },
  routePickerBlock: {
    gap: spacing.xs,
  },
  routePicker: {
    minHeight: 40,
    borderRadius: 22,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border.subtle,
    backgroundColor: colors.surface.backgroundTint,
    padding: 3,
    flexDirection: 'row',
    gap: 3,
  },
  routePickerOption: {
    flex: 1,
    minHeight: 34,
    borderRadius: 18,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  routePickerOptionSelected: {
    backgroundColor: colors.brand.whiteStream,
  },
  routePickerOptionPressed: {
    backgroundColor: colors.surface.pressed,
  },
  routePickerText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 11,
    color: colors.text.secondary,
    textAlign: 'center',
  },
  routePickerTextSelected: {
    color: colors.text.onAccent,
  },
  routePickerTextDisabled: {
    opacity: 0.64,
  },
  warningText: {
    fontFamily: fontFamily.ui,
    fontSize: 13,
    color: colors.semantic.warning,
  },
  claimNote: {
    fontFamily: fontFamily.ui,
    fontSize: 12,
    color: colors.text.secondary,
  },
  payrollBackgroundStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  payrollReceiptList: {
    gap: spacing.xs,
  },
  emptyReceiptCard: {
    minHeight: 74,
    borderRadius: spacing.md,
    borderCurve: 'continuous',
    backgroundColor: colors.glass.clearFill,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rimSubtle,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  emptyReceiptIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderCurve: 'continuous',
    backgroundColor: colors.surface.backgroundTint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyReceiptIconMuted: {
    backgroundColor: colors.glass.frostFill,
  },
  emptyReceiptCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  emptyReceiptTitle: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
  },
  emptyReceiptBody: {
    fontFamily: fontFamily.ui,
    fontSize: 12,
    lineHeight: 17,
    color: colors.text.secondary,
  },
  payrollReceiptRow: {
    minHeight: 38,
    borderRadius: spacing.sm,
    borderCurve: 'continuous',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border.subtle,
    backgroundColor: colors.surface.backgroundTint,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  payrollReceiptRowPressed: {
    opacity: 0.72,
  },
  payrollReceiptLabel: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 12,
    color: colors.text.secondary,
  },
  payrollReceiptHash: {
    flex: 1,
    textAlign: 'right',
    fontFamily: fontFamily.mono,
    fontSize: 12,
    color: colors.text.primary,
  },
  typedConfirmInput: {
    height: 40,
    borderRadius: spacing.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border.strong,
    paddingHorizontal: spacing.md,
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 15,
    color: colors.text.primary,
    backgroundColor: colors.surface.backgroundTint,
  },
  primaryButton: {
    height: 44,
    borderRadius: 22,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.brand.deepShadow,
    flexDirection: 'row',
    gap: spacing.sm,
  },
  primaryButtonDisabled: {
    backgroundColor: 'rgba(16, 16, 16, 0.4)',
  },
  primaryButtonText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 15,
    color: colors.brand.whiteStream,
  },
  secondaryRow: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  payrollActionStack: {
    gap: spacing.sm,
  },
  secondaryButton: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    borderCurve: 'continuous',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing.xs,
    backgroundColor: colors.surface.backgroundTint,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.glass.rim,
  },
  secondaryButtonText: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
  },
  dangerSecondaryButton: {
    borderColor: 'rgba(255, 65, 96, 0.38)',
    backgroundColor: 'rgba(255, 65, 96, 0.18)',
  },
  dangerSecondaryButtonText: {
    color: colors.semantic.error,
  },
  // Row preview list
  rowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.holdingsCard.divider,
  },
  rowLabel: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
  },
  rowRecipient: {
    fontFamily: fontFamily.ui,
    fontSize: 12,
    color: colors.text.secondary,
  },
  rowAmount: {
    fontFamily: fontFamily.uiSemiBold,
    fontSize: 14,
    color: colors.text.primary,
  },
  rowStatus: {
    fontFamily: fontFamily.ui,
    fontSize: 11,
  },
  rowError: {
    fontFamily: fontFamily.ui,
    fontSize: 11,
    color: colors.semantic.error,
    flexShrink: 1,
  },
});
